GRANT SELECT ON Movies TO admi42;
GRANT SELECT ON Temps TO admi42;
GRANT SELECT ON Rating TO admi42;
GRANT SELECT ON Tagging TO admi42;

GRANT SELECT ON Movies TO admi21;
GRANT SELECT ON Temps TO admi21;
GRANT SELECT ON Rating TO admi21;
GRANT SELECT ON Tagging TO admi21;

GRANT SELECT ON Movies TO admi45;
GRANT SELECT ON Temps TO admi45;
GRANT SELECT ON Rating TO admi45;
GRANT SELECT ON Tagging TO admi45;
